services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.12.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /opt/mealie:/app/data/
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Australia/Sydney
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.flodin.net

