services:
  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

 mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      
volumes:
  grafana-data:
    external: true
  mosquitto-data:
    external: true
  mosquitto-conf:
    external: true
