services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - /opt/nginx/data:/data
      - /opt/nginx/letsencrypt:/etc/letsencrypt
  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - duplicati-config:/config
      - /opt:/source
      - /media/USB:/media/USB
    ports:
      - 8200:8200
    restart: unless-stopped
volumes:
  grafana-data:
    external: true
  mosquitto-data:
    external: true
  mosquitto-conf:
    external: true
  influxdb-data:
    external: true
  duplicati-config:
    external: true
