services:
  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:
    external: true
