services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /opt/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3003:3001  # <Host Port>:<Container Port>
    restart: always
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - /opt/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3002:3000"
      - "222:22"
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /opt/heimdall/config:/config
    ports:
      - 88:80
      - 444:443
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  #mosquitto:
 #   image: eclipse-mosquitto:2
  #  restart: unless-stopped
  #  command: mosquitto -c /mosquitto-no-auth.conf
   # ports:
   #   - 1883:1883
   # volumes:
   #   - mosquitto-conf:/mosquitto/config
   #   - mosquitto-data:/mosquitto/data

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - duplicati-config:/config
      - /opt:/source
      - /media/USB:/media/USB
    ports:
      - 8200:8200
    restart: unless-stopped
volumes:
  grafana-data:
    external: true
  mosquitto-data:
    external: true
  mosquitto-conf:
    external: true
  influxdb-data:
    external: true
  duplicati-config:
    external: true
