services:
  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - duplicati-config:/config
      - /opt:/source
    ports:
      - 8200:8200
    restart: unless-stopped

volumes:
  grafana-data:
    external: true
  mosquitto-data:
    external: true
  mosquitto-conf:
    external: true
  influxdb-data:
    external: true
  duplicati-config:
    external: true
