services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/grafana-data
