services:
  signal:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      - AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8095:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "/opt/signal:/home/.local/share/signal-cli" 
