services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    user: "${UID}:${GID}"
    environment:
      - ENCRYPTION_KEY=$ENCRYPTION_KEY
      - DATABASE_USER=teslamate
      - DATABASE_PASS=$POSTGRES_PASSWORD
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
    restart: always
    user: "${UID}:${GID}"
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    user: "${UID}:${GID}"
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=$POSTGRES_PASSWORD
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    user: "${UID}:${GID}"
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
    external: true
  teslamate-grafana-data:
    external: true
  mosquitto-conf:
  mosquitto-data:
